# actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  tomcat:
    threads:
      #最大工作线程数
      max: 200
      #最小工作线程数
      min-spare: 200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.92.117:3306/JavaEELab?serverTimezone=GMT%2B8
    username: root
    password: 15185912234Taq
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #domain对象的包
  type-aliases-package: org.ooda.entity
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    #输出产生的SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

